KAFKA_BOOTSTRAP_SERVERS = ['localhost:29092']
ORDERS_TOPIC = 'orders'
ORDERS_RETRY_TOPIC = 'orders-retry'
ORDERS_DLQ_TOPIC = 'orders-dlq'
CONSUMER_GROUP_ID = 'order-processor-group'
MAX_RETRIES = 3
RETRY_DELAY_SECONDS = 2
PRODUCER_INTERVAL_SECONDS = 2
TOTAL_ORDERS_TO_PRODUCE = 50

TEMP_FAILURE_THRESHOLD = 10.0
PERMANENT_FAILURE_THRESHOLD = 1000.0

PRODUCTS = ["Laptop", "Phone", "Tablet", "Headphones", "Keyboard", "Mouse", "Monitor"]
MIN_PRICE = 5.0
MAX_PRICE = 1500.0